### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MysticTempest** [MysticTempest/MysticTempest-Tea-mod#1]
- [x] Re-check for compatibility with latest SDV(upcoming 1.5.5)
- [x] Update folder names
- [x] Fix issue with default token in springobjects sprites in non-english languages
- [x] Add a few new items to the experimental Botany expansion
- [x] Update documentation for new items, and adjust sell prices of new items
- [ ] Acquire translations
- [ ] Adjust sell prices of new items
- [ ] Re-check for compatibility with upcoming/latest SDV v1.6
